exec((P/'scripts/erpnext-primitives.py').read_text())
s=(P/'scripts/source-ui/result.html').read_text();rail=element_at(s,s.index('<div class="flex w-[58px] shrink-0 flex-col'))
rail=rail.replace('rounded-[10px] border border-[#ededed] bg-white text-[#383838] shadow-sm','rounded-[10px] text-[#737373]')
# Extract the genuine bottom composer from the original docked chat.
s=(P/'scripts/source-ui/request.html').read_text();needle='<div class="relative z-10 flex min-h-[144px]';first=s.index(needle);bottom=element_at(s,s.index(needle,first+1))
checkbox='<i class="erp-check"></i>'
items='<div class="erp-toolbar"><span class="erp-filter wide">Item Code</span><span class="erp-filter">Item Group</span><span class="erp-filter">Filter ▾</span><span style="margin-left:auto" class="erp-button">List View ▾</span></div><div class="erp-list"><div class="erp-list-row erp-list-head"><span>'+checkbox+'</span><span>Item Code</span><span>Item Name</span><span>Item Group</span><span>Status</span></div>'
for i,(code,name,group) in enumerate([('DINING-CHAIR','Dining chair','Products'),('TIMBER','Timber plank','Raw Material'),('WOOD-SCREW','Wood screw','Raw Material'),('WOOD-FINISH','Natural wood finish','Raw Material')]):
 items+=f'<div id="stock-item-{i}" class="erp-list-row"><span>{checkbox}</span><span class="erp-link">{code}</span><span>{name}</span><span>{group}</span><span class="erp-enabled"><i class="erp-dot"></i>Enabled</span></div>'
items+='</div><div class="erp-footer">4 of 4</div>'
item_page=erp_page('setup-items','Item','Stock / Item',items)
warehouse_page=erp_page('setup-warehouses','Warehouse','Stock / Warehouse','<div class="erp-toolbar"><span class="erp-filter wide">Acme Manufacturing ▾</span><span class="erp-button">Expand All</span></div>'+erp_tree([(0,'All Warehouses - AM','Group',True),(1,'Stores - AM','Warehouse',False),(1,'Work In Progress - AM','Warehouse',False),(1,'Finished Goods - AM','Warehouse',False)],'warehouse'),'+ Add Child')
bom='<div class="erp-tabs"><span class="active">Details</span><span>Operations</span><span>Costing</span><span>Connections</span></div><div class="erp-field-row">'+erp_field('Item','DINING-CHAIR · Dining chair')+erp_field('Quantity','1')+'</div><div class="erp-section">Raw Materials</div>'+erp_grid(['No.','Item Code','Item Name','Qty','UOM'],[['1','TIMBER','Timber plank','4','Nos'],['2','WOOD-SCREW','Wood screw','16','Nos'],['3','WOOD-FINISH','Natural wood finish','0.25','Litre']],'bom-material')+'<div style="margin-top:12px"><span class="erp-button">Add Row</span></div><div class="erp-section" style="margin-top:18px">Operations</div>'+erp_grid(['No.','Operation','Workstation','Operation Time','Sequence ID'],[['1','Cutting','Wood cutting','20 min','1'],['2','Assembly','Assembly bench','35 min','2']],'bom-operation')
bom_page=erp_page('setup-bom','BOM-DINING-CHAIR-001<span class="erp-badge">Active</span>','Manufacturing / BOM',bom,'Actions ▾')
accounts=[(0,'Application of Funds (Assets) - AM','Group',True),(1,'Current Assets - AM','Group',True),(2,'Stock Assets - AM','Group',True),(3,'Stock In Hand - AM','Stock',False),(2,'Bank Accounts - AM','Group',False),(0,'Expenses - AM','Group',True),(1,'Direct Expenses - AM','Group',True),(2,'Stock Expenses - AM','Group',True),(3,'Cost of Goods Sold - AM','Expense',False)]
account_page=erp_page('setup-accounts','Chart of Accounts','Accounts / Chart of Accounts','<div class="erp-toolbar"><span class="erp-filter wide">Acme Manufacturing ▾</span><span class="erp-button">Expand All</span></div>'+erp_tree(accounts,'account'),'+ Add Child')
